---
name: Helm Loki Diff CI
on: [pull_request]
    # paths:
    #   - "production/helm/loki/**"

jobs:
  publish-diff:
    name: Publish Rendered Helm Chart Diff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Add required Helm repositories
        run: |
          helm repo add minio https://charts.min.io/
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add grafana-operator https://grafana.github.io/helm-charts
          helm repo update

      - name: Setup K3D
        uses: ./.github/actions/setup-k3d

      - name: Setup Helm plugins
        run: |
          helm plugin install https://github.com/databus23/helm-diff

      - name: Build helm dependencies
        run: |
          helm dependency build production/helm/loki

      - name: Install latest helm release
        run: |
          helm install --create-namespace loki-release grafana/loki -f production/helm/loki/scenarios/default-single-binary-values.yaml --version 6.21.0

      - name: Run helm diff
        id: helm-diff
        env:
          HELM_DIFF_USE_UPGRADE_DRY_RUN: true
        run: |
          helm diff upgrade loki-release -f production/helm/loki/scenarios/default-single-binary-values.yaml production/helm/loki | tee helm_diff_output.txt

      - name: Publish artifact with diff
        uses: actions/upload-artifact@v4
        id: diff_artifact
        with:
          name: helm_diff_output
          path: helm_diff_output.txt
          retention-days: 3

      - name: Post Helm Diff artifact link as comment
        uses: actions/github-script@v6
        with:
          script: |
            const artifactName = 'helm-diff-output';
            const runId = context.runId;
            const artifactUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/suites/${runId}/artifacts`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `### Helm Diff Artifact\nYou can download the artifact [here](${artifactUrl}).`
            });
